apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - mountPath: /usr/share/nginx/html/sudhams.html
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /root/share-data/sudhams.html
      # this field is optional
      type: FileOrCreate 
