apiVersion: v1
kind: Pod 
metadata:
  name: redis
spec:
  volumes:
  - name: redis-storage
    emptyDir: {}
  containers:
  - name: redis 
    image: redis 
    volumeMounts:
    - name: redis-storage
      mountPath: /data/redis 

