apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test
  labels:
    app: guestbook
    tier: test
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: test
  template:
    metadata:
      labels:
        tier: test
    spec:
      containers:
      - name: test
        image: nginx
