apiVersion: v1
kind: Pod
metadata:	   
  name: sample-pod
  namespace: default 
  labels:
    app: nginx-mysql
    test: shiva
spec:
  containers:
  - name: mysql
    image: mysql
    ports:
    - containerPort: 3306
    env: 
    - name: MYSQL_ROOT_PASSWORD
      value: "test123"
    resources: 
      requests:
        cpu: "250m"
        memory: "400M"
      limits: 
        cpu: "350m"
        memory: "500M"
  - name: shiva 
    image: nginx
    ports:
    - containerPort: 80
    env:
     - name: APACHE_HOME
       value: "/etc/apache2"
